# SDK 文档构建配置文件
project:
  name: "psoc_e84-edgi-talk SDK"
  title: "psoc_e84-edgi-talk"
  description: "Edgi-Talk 开发板基于 PSoC™ E84 MCU，为工程师提供了一个灵活、全面的开发平台。板上集成了丰富的外设接口和示例模块，助力开发者快速完成多传感器、显示和通信应用的开发。"
  description_en: "The Edgi-Talk board is based on the PSoC™ E84 MCU and provides a flexible and comprehensive development platform.It integrates a variety of peripheral interfaces and sample modules, helping developers quickly implement applications involving multi-sensor integration, display, and communication."
  version: "1.0.0"
  author: "PeterJhon"
  copyright: "Copyright (c) 2006-2025, RT-Thread Development Team"
  # language: "zh_CN" 
  website: "www.rt-thread.org"

# 仓库配置
repository:
  name: "sdk-bsp-psoc_e84-edgi-talk"
  projects_dir: "../../projects"
  docs_dir: "."

# 文档分类配置
categories:
  basic:
    name: "基础篇"
    name_en: "Basics"
    description: "基础功能"
    patterns:
      - "Edgi-Talk_Blink_Led/Edgi_Talk_M33_Blink_LED"
      - "Edgi-Talk_Blink_Led/Edgi_Talk_M55_Blink_LED"
      - "Edgi-Talk_M33_S_Template/Edgi_Talk_M33_S_Template"
      - "Edgi-Talk_M33_Template/Edgi_Talk_M33_Template"
  driver:
    name: "驱动篇"
    name_en: "Drivers"
    description: "外设驱动"
    patterns:
      - "Edgi-Talk_ADC/Edgi_Talk_M33_ADC"
      - "Edgi-Talk_AHT20/Edgi_Talk_M33_AHT20"
      - "Edgi-Talk_Audio/Edgi_Talk_M33_Audio"
      - "Edgi-Talk_emUSB-device_CDC_Echo/Edgi_Talk_M33_emUSB-device_CDC_Echo"
      - "Edgi-Talk_HyperRam/Edgi_Talk_M33_HyperRam"
      - "Edgi-Talk_HyperRam/Edgi_Talk_M33_S_HyperRam"
      - "Edgi-Talk_Key_Irq/Edgi_Talk_M33_Key_Irq"
      - "Edgi-Talk_LSM6DS3/Edgi_Talk_M33_LSM6DS3"
      - "Edgi-Talk_MIPI_LCD/Edgi_Talk_M55_MIPI_LCD"
      - "Edgi-Talk_RTC/Edgi_Talk_M33_RTC"
      - "Edgi-Talk_SDCARD/Edgi_Talk_M33_SDCARD"
      - "Edgi-Talk_WIFI/Edgi_Talk_M55_WIFI"
  component:
    name: "示例"
    name_en: "Example"
    description: "示例"
    patterns:
      - "Edgi-Talk_CoreMark/Edgi_Talk_M55_CoreMark"
      - "Edgi-Talk_LVGL/Edgi_Talk_M55_LVGL"
      - "Edgi-Talk_WavPlayer/Edgi_Talk_M33_WavPlayer"
      - "Edgi-Talk_XiaoZhi/Edgi_Talk_M55_XiaoZhi"
# 文档生成配置
generation:
  copy_files:
    - "README.md"
    - "README_zh.md"
  copy_dirs:
    - "figures"
  output_structure:
    - "start"
    - "basic"
    - "driver"
    - "component"
    - "protocol"

# Sphinx 配置
sphinx:
  theme: "sphinx_rtd_theme"
  extensions:
    - "myst_parser"
  source_suffix:
    ".rst": "restructuredtext"
    ".md": "markdown"
  myst_extensions:
    - "colon_fence"
    - "deflist"
    - "dollarmath"
    - "html_image"
    - "html_admonition"
    - "replacements"
    - "smartquotes"
    - "strikethrough"
    - "substitution"
    - "tasklist" 
