
#ifndef RTCONFIG_PREINC_H__
#define RTCONFIG_PREINC_H__

/* Automatically generated file; DO NOT EDIT. */
/* RT-Thread pre-include file */

#define APP_SOCMEMSRAM_CM55NS_APP_SIZE 0x00060800
#define APP_SOCMEMSRAM_GPUBUF_SHARED_SIZE 0x0001F800
#define APP_SOCMEMSRAM_GPUBUF_SIZE 0x00300000
#define COMPONENT_CAT1
#define COMPONENT_CAT1D
#define COMPONENT_CM33
#define COMPONENT_CM33_0
#define COMPONENT_GCC_ARM
#define COMPONENT_MTB_DEVICE_SUPPORT
#define COMPONENT_MTB_HAL
#define COMPONENT_MW_ASYNC_TRANSFER
#define COMPONENT_MW_CMSIS
#define COMPONENT_MW_CORE_LIB
#define COMPONENT_MW_CORE_MAKE
#define COMPONENT_MW_MTB_DEVICE_SUPPORT_PSE8XXGP
#define COMPONENT_MW_RETARGET_IO
#define COMPONENT_NON_SECURE_DEVICE
#define COMPONENT_PSE84
#define COMPONENT_SOFTFP
#define CORE_NAME_CM33_0 1
#define CY_PDL_FLASH_BOOT
#define CY_RETARGET_IO_CONVERT_LF_TO_CRLF
#define CY_SUPPORTS_DEVICE_VALIDATION
#define CY_TARGET_BOARD APP_KIT_PSE84_EVAL_EPC2
#define FLASH_BOOT
#define PSE846GPS2DBZC4A
#define RT_USING_LIBC
#define RT_USING_NEWLIBC
#define TARGET_APP_KIT_PSE84_EVAL_EPC2
#define _POSIX_C_SOURCE 1
#define __RTTHREAD__

#endif /*RTCONFIG_PREINC_H__*/
